Resources:
  {{ nameCamel }}Table:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: ${self:custom.deletionPolicy.${opt:stage}}
    UpdateReplacePolicy: ${self:custom.updatePolicy.${opt:stage}}
    Properties:
      TableName: ${env:APP_NAME}-${opt:stage}-{{ nameKebab }}
      AttributeDefinitions:
        - AttributeName: {{ primaryKey }}
          AttributeType: S
      KeySchema:
        - AttributeName: {{ primaryKey }}
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification: 
        PointInTimeRecoveryEnabled: true
