Resources:
  BedrockAgentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${env:APP_NAME}-${opt:stage}-bedrock-agent-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: BedrockAgentPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                Resource:
                  - arn:aws:bedrock:*::foundation-model/*
                  - arn:aws:bedrock:${opt:region}:*:*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess

Outputs:
  BedrockAgentRoleArn:
    Description: ARN of the Bedrock Agent IAM Role
    Value: !GetAtt BedrockAgentRole.Arn
    Export:
      Name: ${env:APP_NAME}-${opt:stage}-BedrockAgentRoleArn
