Resources:
  AssetBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${env:APP_NAME}-${opt:stage}-asset
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedHeaders:
              - '*'
            ExposedHeaders:
              - ETag
              - x-amz-request-id
              - x-amz-id-2
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
